### ISSUE TITLE
font-face.less  怎么使用

### ISSUE THREAD

**Issue by liaohui1080** [Aaaaaashu/Rhythm#1]
font-face.less  怎么使用 
能举个例子吗

**Comment by Aaaaaashu** [comment]
比如 `font-family: "Helvetica Neue", Helvetica, Arial, "Rhythm Heiti", sans-serif;` 
这样能理解吗？

**Comment by liaohui1080** [comment]
明白了


原始邮件
发件人:阿树notifications@github.com
收件人:Aaaaaashu/RhythmRhythm@noreply.github.com
抄送:china girlmy300ge@gmail.com
发送时间:2016年1月28日(周四) 16:28
主题:Re: [Rhythm] font-face.less 怎么使用 (#1)


比如 font-family: "Helvetica Neue", Helvetica, Arial, "Rhythm Heiti", sans-serif; 
 这样能理解吗？
